# Generated by Django 3.2.2 on 2021-05-13 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
                ('where', models.CharField(max_length=100)),
                ('timings', models.CharField(max_length=100)),
            ],
        ),
    ]
