# Generated by Django 3.0.3 on 2021-05-07 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0002_auto_20210507_1042'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Electronics',
        ),
    ]
