# Generated by Django 3.2.2 on 2021-05-12 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0004_rename_electrics_samsung'),
    ]

    operations = [
        migrations.CreateModel(
            name='samsungw',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
    ]
