# Generated by Django 3.2.2 on 2021-05-12 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0005_samsungw'),
    ]

    operations = [
        migrations.CreateModel(
            name='samsungp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('height', models.IntegerField(max_length=1000)),
                ('width', models.CharField(max_length=1001)),
                ('name', models.CharField(max_length=200)),
                ('summary', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='samsung',
        ),
        migrations.DeleteModel(
            name='samsungw',
        ),
    ]
