# Generated by Django 3.2.2 on 2021-05-12 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0006_auto_20210512_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='samsungp',
            name='price',
            field=models.IntegerField(default=15000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samsungp',
            name='height',
            field=models.IntegerField(),
        ),
    ]
