# Generated by Django 3.2.2 on 2021-05-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('electronics', '0010_epsonp'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=500)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
